                                                                                                                                                                                                                                                               
MIME-Version: 1.0
Sender: vbputz@gmail.com
Received: by 10.202.87.22 with HTTP; Tue, 4 Aug 2015 04:19:13 -0700 (PDT)
Date: Tue, 4 Aug 2015 11:19:13 +0000
Delivered-To: vbputz@gmail.com
X-Google-Sender-Auth: HBWxZBMEYbC6gIuxqJO9rG6Oxi4
Message-ID: <CADsvd-RtEgY40DtkdwKAZNUYPByO98FPnas8heK2J4LsYuaWWw@mail.gmail.com>
Subject: perdiem
From: Vic Putz <vputz@nyx.net>
To: cary@thingotron.com
Content-Type: text/plain; charset=UTF-8

brugges. belgium
